### ISSUE TITLE
set up CI for testing

### ISSUE THREAD

**Issue by CSchank** [dalvescb/HashedExpression#25]

**Comment by CSchank** [comment]
The Stack documentation gives some example config files for Travis CI. I am planning to optimize them for our purposes. Here is my proposal. I'd like some feedback. Travis spins up a virtual machine to check our code in ways we configure, sending results back to GitHub to, for example, disallow pull requests if something fails. It is automatic and triggered by things like pushes and pull requests being issued. 

**When committing to normal branches:**
1. Build with the project's default stack version
2. Check hindent
3. Run through haddock checker to ensure public things are documented properly.
If these fail, the build will fail, helping the developer to fix those issues before issuing a PR. 

**When issuing pull requests or commits to `develop`:**
1. Build with the project's default version of stack
2. Check hindent
3. Run through haddock checker to ensure public things are documented properly.
Either of these failing will cause the PR to be un-mergeable until they are fixed.

**When issuing pull requests (and commits) to `master` (from `develop` probably):**
1. Check build with many versions of stack (e.g. LTS-9, 10, 11, 12} (and, if we decide to support it, cabal)
2. Check hindent
3. Check haddock documentation again.
Don't allow merging until these are fixed. 

In all cases, administrators have the right to force merges if it is deemed necessary / okay to do so. This will be on a case-by-case basis, but the aim is to help developers write better code before it makes it to the develop and especially master branches.

Let me know if I've missed anything or if you have suggestions.

**Comment by dandoh** [comment]
Sounds good to me!!
